name: FlickFormatter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --name "FlickFormatter" renamer.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: Python-EXE
        path: dist/FlickFormatter.exe
